/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as FruitsRouteImport } from './routes/fruits'
import { Route as FormRouteImport } from './routes/form'
import { Route as FetchDataRouteImport } from './routes/fetchData'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'

const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const FruitsRoute = FruitsRouteImport.update({
  id: '/fruits',
  path: '/fruits',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const FetchDataRoute = FetchDataRouteImport.update({
  id: '/fetchData',
  path: '/fetchData',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/fetchData': typeof FetchDataRoute
  '/form': typeof FormRoute
  '/fruits': typeof FruitsRoute
  '/payment': typeof PaymentRoute
  '/repositories': typeof RepositoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/fetchData': typeof FetchDataRoute
  '/form': typeof FormRoute
  '/fruits': typeof FruitsRoute
  '/payment': typeof PaymentRoute
  '/repositories': typeof RepositoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/fetchData': typeof FetchDataRoute
  '/form': typeof FormRoute
  '/fruits': typeof FruitsRoute
  '/payment': typeof PaymentRoute
  '/repositories': typeof RepositoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/fetchData'
    | '/form'
    | '/fruits'
    | '/payment'
    | '/repositories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/fetchData'
    | '/form'
    | '/fruits'
    | '/payment'
    | '/repositories'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/fetchData'
    | '/form'
    | '/fruits'
    | '/payment'
    | '/repositories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  FetchDataRoute: typeof FetchDataRoute
  FormRoute: typeof FormRoute
  FruitsRoute: typeof FruitsRoute
  PaymentRoute: typeof PaymentRoute
  RepositoriesRoute: typeof RepositoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruits': {
      id: '/fruits'
      path: '/fruits'
      fullPath: '/fruits'
      preLoaderRoute: typeof FruitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fetchData': {
      id: '/fetchData'
      path: '/fetchData'
      fullPath: '/fetchData'
      preLoaderRoute: typeof FetchDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  FetchDataRoute: FetchDataRoute,
  FormRoute: FormRoute,
  FruitsRoute: FruitsRoute,
  PaymentRoute: PaymentRoute,
  RepositoriesRoute: RepositoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
